Repository hashicorp/terraform-provider-azuread, pull requests merged in 2019-07, with the labels that each got.

#115 azuread_application: Allow all valid app identifier URI schemes
  azuread/helpers/validate/url.go
  azuread/helpers/validate/url_test.go
  azuread/resource_application.go
Labels: size/S

#114 azuread user - import example
  website/docs/r/user.html.markdown
Labels: documentation, feature/users, size/XS

#113 run terrafmt on website & acctest tf blocks
  azuread/data_user_test.go
  azuread/data_users_test.go
  azuread/resource_application_test.go
  azuread/resource_user_test.go
  website/docs/auth/service_principal_client_certificate.html.markdown
  website/docs/auth/service_principal_client_secret.html.markdown
  website/docs/d/user.html.markdown
  website/docs/d/users.html.markdown
  website/docs/r/application.html.markdown
  website/docs/r/application_password.html.markdown
  website/docs/r/service_principal.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, refactor, size/XL

#100 Resource: 'azuread_group_member'
  azuread/helpers/graph/group.go
  azuread/helpers/slices/slices.go
  azuread/provider.go
  azuread/resource_group.go
  azuread/resource_group_member.go
  azuread/resource_group_member_test.go
  azuread/resource_group_test.go
  website/azuread.erb
  website/docs/r/group.markdown
  website/docs/r/group_member.markdown
Labels: documentation, feature/groups, size/XL

#118 azuread_application_password: add replication wait
  azuread/helpers/graph/credentials.go
  azuread/helpers/graph/replication.go
  azuread/resource_application_password.go
Labels: bug, feature/application, size/S

#117 Wait on password replication
  azuread/resource_application_password.go
  azuread/resource_service_principal_password.go
Labels: bug, feature/service-principal, size/XS, waiting-response

#121 azuread_application - support for the public_client property
  azuread/resource_application.go
  azuread/resource_application_test.go
  website/docs/r/application.html.markdown
Labels: documentation, enhancement, feature/application, size/M

#124 Update tests to be consistant
  azuread/data_application_test.go
  azuread/data_service_principal_test.go
  azuread/resource_application_password_test.go
  azuread/resource_application_test.go
  azuread/resource_service_principal_password_test.go
  azuread/resource_service_principal_test.go
  azuread/resource_user_test.go
Labels: size/M, tests

#123 documentation: rename resources from test -> example
  website/docs/d/application.html.markdown
  website/docs/d/group.html.markdown
  website/docs/d/groups.html.markdown
  website/docs/d/service_principal.html.markdown
  website/docs/d/user.html.markdown
  website/docs/r/application.html.markdown
  website/docs/r/group.markdown
  website/docs/r/group_member.markdown
  website/docs/r/service_principal.html.markdown
  website/docs/r/service_principal_password.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, size/M

#125 Add -All $true to Get-AzureADServicePrincipal
  website/docs/auth/service_principal_configuration.html.markdown
Labels: documentation, size/XS

#62 azuread_group - support for the `owners` property
  azuread/data_group.go
  azuread/data_group_test.go
  azuread/data_users_test.go
  azuread/helpers/ar/response.go
  azuread/helpers/graph/credentials.go
  azuread/helpers/graph/group.go
  azuread/helpers/graph/object_resource.go
  azuread/helpers/tf/locks.go
  azuread/helpers/validate/strings_test.go
  azuread/locks.go
  azuread/provider.go
  azuread/resource_application_password.go
  azuread/resource_group.go
  azuread/resource_group_member.go
  azuread/resource_group_member_test.go
  azuread/resource_group_test.go
  azuread/resource_service_principal_password.go
  azuread/resource_user_test.go
  website/docs/r/group.markdown
  website/docs/r/group_member.markdown
Labels: documentation, feature/groups, size/XL

#129 azuread_application_password: fix incorrect conflicts with
  azuread/resource_application_password.go
Labels: bug, feature/application, size/XS
