Repository hashicorp/terraform-provider-azuread, pull requests merged in 2019-12, with the labels that each got.

#179 website: Move auth guides to guides/ folder
  website/azuread.erb
  website/docs/guides/azure_cli.html.markdown
  website/docs/guides/managed_service_identity.html.markdown
  website/docs/guides/service_principal_client_certificate.html.markdown
  website/docs/guides/service_principal_client_secret.html.markdown
  website/docs/guides/service_principal_configuration.html.markdown
  website/docs/index.html.markdown
  website/docs/r/service_principal.html.markdown
Labels: documentation, size/S

#184 fix: Updating doc to 0.7.0 release
  website/docs/index.html.markdown
Labels: documentation, size/XS

#190 azuread_groups - sidebar and doc fix
  website/azuread.erb
  website/docs/d/groups.html.markdown
Labels: documentation, feature/groups, size/XS
