Repository hashicorp/terraform-provider-azuread, pull requests merged in 2019-06, with the labels that each got.

#93 enhance application and SP replication wait
  azuread/provider.go
  azuread/resource_application.go
  azuread/resource_service_principal.go
Labels: bug, feature/application, feature/service-principal, size/M

#91 azuread_[group|user]: wait for replication
  azuread/helpers/graph/replication.go
  azuread/provider.go
  azuread/resource_application.go
  azuread/resource_group.go
  azuread/resource_service_principal.go
  azuread/resource_user.go
Labels: bug, feature/groups, feature/users, size/M

#90 data.azuread_[group|user]: add lookup by object_id
  azuread/data_application.go
  azuread/data_domains.go
  azuread/data_group.go
  azuread/data_group_test.go
  azuread/data_user.go
  azuread/data_user_test.go
  website/docs/d/group.html.markdown
  website/docs/d/service_principal.html.markdown
  website/docs/d/user.html.markdown
Labels: documentation, enhancement, feature/groups, feature/users, refactor, size/L

#97 go mod tidy
  go.mod
  go.sum
  vendor/github.com/gofrs/uuid/.gitignore
  vendor/github.com/gofrs/uuid/.travis.yml
  vendor/github.com/gofrs/uuid/LICENSE
  vendor/github.com/gofrs/uuid/README.md
  vendor/github.com/gofrs/uuid/codec.go
  vendor/github.com/gofrs/uuid/fuzz.go
  vendor/github.com/gofrs/uuid/generator.go
  vendor/github.com/gofrs/uuid/sql.go
  vendor/github.com/gofrs/uuid/uuid.go
  vendor/modules.txt
Labels: dependencies, size/XXL, technical-debt

#99 add explicit object_id property to resources
  azuread/data_application_test.go
  azuread/data_group_test.go
  azuread/data_service_principal_test.go
  azuread/data_user_test.go
  azuread/resource_application.go
  azuread/resource_application_test.go
  azuread/resource_group.go
  azuread/resource_group_test.go
  azuread/resource_service_principal.go
  azuread/resource_service_principal_test.go
  azuread/resource_user.go
  azuread/resource_user_test.go
  website/docs/d/group.html.markdown
  website/docs/r/application.html.markdown
  website/docs/r/service_principal.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, enhancement, size/S

#102 Upgrade azure-sdk-for-go to v29.0.0
  azuread/config.go
  azuread/data_application.go
  azuread/data_application_test.go
  azuread/helpers/ar/sender.go
  azuread/resource_application.go
  azuread/resource_application_test.go
  azuread/resource_service_principal.go
  go.mod
  go.sum
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/applications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/oauth2.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/oauth2permissiongrant.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token.go
  vendor/github.com/Azure/go-autorest/autorest/adal/version.go
  vendor/github.com/Azure/go-autorest/autorest/authorization.go
  vendor/github.com/Azure/go-autorest/autorest/azure/async.go
  vendor/github.com/Azure/go-autorest/autorest/azure/cli/token.go
  vendor/github.com/Azure/go-autorest/autorest/azure/environments.go
  vendor/github.com/Azure/go-autorest/autorest/client.go
  vendor/github.com/Azure/go-autorest/autorest/version.go
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_azure_cli_token.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_client_cert.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_client_secret.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/auth_method_msi.go
  vendor/github.com/hashicorp/go-azure-helpers/authentication/config.go
  vendor/modules.txt
Labels: dependencies, size/XXL, upstream-microsoft

#105 tune goimports linting
  .golangci.yml
  GNUmakefile
  azuread/config.go
  azuread/data_group.go
  azuread/data_user.go
  azuread/helpers/ar/response_test.go
  azuread/helpers/graph/credentials.go
  azuread/helpers/graph/replication.go
  azuread/resource_application.go
  azuread/resource_application_password.go
  azuread/resource_application_password_test.go
  azuread/resource_application_test.go
  azuread/resource_group.go
  azuread/resource_group_test.go
  azuread/resource_service_principal.go
  azuread/resource_service_principal_password.go
  azuread/resource_user.go
  azuread/resource_user_test.go
  examples/service_principal/basic/main.tf
  examples/service_principal/create-for-rbac/main.tf
  website/docs/auth/service_principal_configuration.html.markdown
Labels: documentation, enhancement, size/S, tests

#103 `azuread_service_principal`: export the `oauth2_permissions` property
  azuread/data_application.go
  azuread/data_service_principal.go
  azuread/data_service_principal_test.go
  azuread/helpers/graph/application.go
  azuread/resource_application.go
  azuread/resource_service_principal.go
  azuread/resource_service_principal_test.go
  website/docs/d/service_principal.html.markdown
  website/docs/r/service_principal.html.markdown
Labels: documentation, feature/service-principal, size/L

#98 Feature/application app roles
  azuread/resource_application.go
  azuread/resource_application_test.go
  website/docs/r/application.html.markdown
Labels: documentation, size/XL, waiting-response

#107 azuread_application_password: deprecate application_id in favour of application_object_id
  azuread/data_service_principal.go
  azuread/data_user_test.go
  azuread/resource_application.go
  azuread/resource_application_password.go
  azuread/resource_application_password_test.go
  azuread/resource_application_test.go
  azuread/resource_service_principal.go
  azuread/resource_service_principal_password_test.go
  azuread/resource_service_principal_test.go
  azuread/resource_user_test.go
  website/docs/r/application_password.html.markdown
Labels: documentation, feature/application, size/L

#110 azuread_application & azuread_service_principal: export the `app_roles` property
  azuread/data_application.go
  azuread/data_application_test.go
  azuread/data_service_principal.go
  azuread/data_service_principal_test.go
  azuread/helpers/graph/application.go
  azuread/resource_application.go
  website/docs/d/application.html.markdown
  website/docs/d/service_principal.html.markdown
Labels: documentation, size/L

#109 New Data Source: azuread_users
  azuread/data_user.go
  azuread/data_user_test.go
  azuread/data_users.go
  azuread/data_users_test.go
  azuread/helpers/graph/user.go
  azuread/helpers/tf/acctest.go
  azuread/helpers/tf/acctest_test.go
  azuread/provider.go
  azuread/resource_application.go
  azuread/resource_user_test.go
  website/azuread.erb
  website/docs/d/user.html.markdown
  website/docs/d/users.html.markdown
Labels: documentation, new-data-source, size/XL

#111 capture current hashibot config
  .hashibot.hcl
Labels: size/XS
