Repository hashicorp/terraform-provider-azuread, pull requests merged in 2019-01, with the labels that each got.

#2 re-feature-toggling the requires import functionality
  azuread/data_application.go
  azuread/data_application_test.go
  azuread/feature_flags.go
  azuread/resource_service_principal_password.go
  azuread/resource_service_principal_password_test.go
Labels: size/S

#3 Adding an example of provisioning a Service Principal
  .travis.yml
  GNUmakefile
  examples/service-principal/README.md
  examples/service-principal/main.tf
Labels: documentation, size/M

#12 adding the `azure providers` to the sidebar
  website/azuread.erb
  website/docs/index.html.markdown
Labels: documentation, size/XS

#20 update linting to use staticcheck instead of unused and megacheck
  .gometalinter.json
  staticcheck.conf
Labels: refactor, size/XS

#22 Remove some unused code & packages
  azuread/helpers/az/resource_group.go
  azuread/helpers/az/resource_group_test.go
  azuread/helpers/az/resourceid.go
  azuread/helpers/az/resourceid_test.go
  azuread/helpers/az/validate.go
  azuread/helpers/az/validate_test.go
  vendor/github.com/hashicorp/go-azure-helpers/resourceproviders/registration.go
  vendor/github.com/hashicorp/terraform/helper/acctest/acctest.go
  vendor/github.com/hashicorp/terraform/helper/acctest/random.go
  vendor/github.com/hashicorp/terraform/helper/acctest/remotetests.go
  vendor/vendor.json
Labels: dependencies, refactor, size/XL

#25 Upgrade azure-sdk-for-go from v21.3.0 -> v24.1.0
  vendor/github.com/Azure/azure-sdk-for-go/profiles/2017-03-09/resources/mgmt/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/applications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/deletedapplications.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/domains.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/groups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/oauth2.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/objects.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/serviceprincipals.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/signedinuser.go
  vendor/github.com/Azure/azure-sdk-for-go/services/graphrbac/1.6/graphrbac/users.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources/deploymentoperations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources/deployments.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources/groups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources/providers.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources/resources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2016-02-01/resources/tags.go
  vendor/github.com/Azure/azure-sdk-for-go/version/version.go
  vendor/vendor.json
Labels: dependencies, size/XXL

#21 azuread_application: correctly read reply URL's from SDK
  azuread/data_application.go
  azuread/helpers/tf/marshall.go
  azuread/resource_application.go
  azuread/resource_application_test.go
Labels: bug, feature/application, size/M

#14 New resource & data source 'azuread_group'
  azuread/config.go
  azuread/data_source_group.go
  azuread/data_source_group_test.go
  azuread/provider.go
  azuread/resource_group.go
  azuread/resource_group_test.go
  website/azuread.erb
  website/docs/d/group.html.markdown
  website/docs/r/group.markdown
Labels: documentation, feature/groups, new-data-source, new-resource, size/XL

#28 d/group: fixing a crash where the `object_id` field no longer exists
  azuread/data_group.go
  azuread/data_group_test.go
  website/docs/r/group.markdown
Labels: bug, documentation, feature/groups, size/XS

#23 azuread_application: Added support for Required Resource Access
  azuread/data_application.go
  azuread/data_application_test.go
  azuread/resource_application.go
  azuread/resource_application_test.go
  website/docs/d/application.html.markdown
  website/docs/r/application.html.markdown
Labels: documentation, feature/application, size/L
