Repository hashicorp/terraform-provider-azuread, pull requests merged in 2020-03, with the labels that each got.

#221 Update service_principal_password.html.markdown
  website/docs/r/service_principal_password.html.markdown
Labels: documentation, feature/service-principal, size/XS

#213 Update data_group outputs in docs (#196)
  website/docs/d/group.html.markdown
Labels: documentation, feature/groups, size/XS

#222 azuread_user - add `onpremises_sam_account_name` and `onpremises_user_principal_name`
  azuread/data_user.go
  azuread/resource_user.go
  website/docs/d/user.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, feature/users, size/S

#207 azuread_user support for immutable_id property
  azuread/data_user.go
  azuread/helpers/p/p.go
  azuread/resource_user.go
  azuread/resource_user_test.go
  website/docs/d/user.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, enhancement, feature/users, size/M, waiting-response

#224 provider - add more linting from azurerm
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .golangci.yml
  .travis.yml
  GNUmakefile
  azuread/data_application_test.go
  azuread/data_group.go
  azuread/data_group_test.go
  azuread/data_groups.go
  azuread/data_groups_test.go
  azuread/helpers/graph/credentials.go
  azuread/resource_application.go
  azuread/resource_application_test.go
  azuread/resource_group.go
  azuread/resource_group_member.go
  azuread/resource_group_member_test.go
  azuread/resource_group_test.go
  go.sum
  main.go
  scripts/terrafmt-acctests.sh
  scripts/terrafmt-website.sh
  website/allowed-subcategories
  website/docs/d/application.html.markdown
  website/docs/d/domains.html.markdown
  website/docs/d/group.html.markdown
  website/docs/d/groups.html.markdown
  website/docs/d/service_principal.html.markdown
  website/docs/d/user.html.markdown
  website/docs/d/users.html.markdown
  website/docs/guides/azure_cli.html.markdown
  website/docs/guides/managed_service_identity.html.markdown
  website/docs/guides/service_principal_client_certificate.html.markdown
  website/docs/guides/service_principal_client_secret.html.markdown
  website/docs/guides/service_principal_configuration.html.markdown
  website/docs/index.html.markdown
  website/docs/r/application.html.markdown
  website/docs/r/application_password.html.markdown
  website/docs/r/group.markdown
  website/docs/r/group_member.markdown
  website/docs/r/service_principal.html.markdown
  website/docs/r/service_principal_password.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, provider, size/L, tests

#216 azuread_group - support for the description property
  azuread/data_group.go
  azuread/resource_group.go
  azuread/resource_group_test.go
  website/docs/d/group.html.markdown
  website/docs/r/group.markdown
Labels: documentation, feature/groups, size/M

#211 azuread_group - owners is now additive on creation allowing existing owner to be in owners list
  azuread/resource_group.go
Labels: bug, feature/groups, size/XS

#227 azuread_group_member - mark as missing when member cannot be found
  azuread/resource_group_member.go
Labels: bug, feature/groups, size/XS

#228 azuread_application_password & azuread_service_principal_password - validate length < 863
  azuread/helpers/graph/credentials.go
  azuread/resource_application_password.go
Labels: bug, feature/application, feature/service-principal, size/XS

#226 azuread_application - add logout_url & fix owner add/delete order
  azuread/data_application.go
  azuread/resource_application.go
  azuread/resource_application_test.go
  website/docs/d/application.html.markdown
  website/docs/r/application.html.markdown
Labels: bug, documentation, enhancement, feature/application, size/L
