Repository hashicorp/terraform-provider-azuread, pull requests merged in 2020-01, with the labels that each got.

#197 Update go version in docs
  README.md
Labels: size/XS

#198 Update readme
  README.md
Labels: size/XS

#204 azuread_application - Add Missing Documentation for Owner Arguments
  website/docs/d/application.html.markdown
  website/docs/r/application.html.markdown
Labels: documentation, feature/application, size/XS

#202 Fixes #201. Changed date to 2099 to prevent issue.
  azuread/resource_application_password_test.go
  azuread/resource_service_principal_password_test.go
  website/docs/r/application_password.html.markdown
  website/docs/r/service_principal_password.html.markdown
Labels: documentation, size/XS
