Repository hashicorp/terraform-provider-azuread, pull requests merged in 2021-06, with the labels that each got.

#446 docs/data-sources/groups.md: Fix property name that wasn't renamed
  docs/data-sources/groups.md
Labels: documentation

#448 microsoft-graph.md: Simplify PowerShell command
  docs/guides/microsoft-graph.md
Labels: documentation

#456 Run tests with Terraform v1.0.0
  .teamcity/components/settings.kt
Labels: tests

#444 Bugfix: enable specifying metadata for app and SP passwords
  docs/guides/microsoft-graph.md
  docs/resources/application_password.md
  docs/resources/service_principal_password.md
  go.mod
  go.sum
  internal/services/applications/application_password_resource_msgraph.go
  internal/services/applications/application_password_resource_test.go
  internal/services/serviceprincipals/service_principal_password_resource_msgraph.go
  internal/services/serviceprincipals/service_principal_password_resource_test.go
  vendor/github.com/manicminer/hamilton/auth/cache.go
  vendor/github.com/manicminer/hamilton/msgraph/app_role_assignments.go
  vendor/github.com/manicminer/hamilton/msgraph/applications.go
  vendor/github.com/manicminer/hamilton/msgraph/groups.go
  vendor/github.com/manicminer/hamilton/msgraph/models.go
  vendor/github.com/manicminer/hamilton/msgraph/serviceprincipals.go
  vendor/github.com/manicminer/hamilton/msgraph/users.go
  vendor/modules.txt
Labels: api/microsoft-graph, bug, feature/application, feature/service-principal

#454 Bugfix: Enable setting >20 group owners or members at create time
  go.mod
  go.sum
  internal/services/groups/group_resource_msgraph.go
  internal/services/groups/group_resource_test.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.s
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/curve25519_amd64.go
  vendor/golang.org/x/crypto/curve25519/curve25519_amd64.s
  vendor/golang.org/x/crypto/curve25519/curve25519_generic.go
  vendor/golang.org/x/crypto/curve25519/curve25519_noasm.go
  vendor/golang.org/x/crypto/curve25519/internal/field/README
  vendor/golang.org/x/crypto/curve25519/internal/field/fe.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.s
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64_noasm.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64.s
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64_noasm.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_generic.go
  vendor/golang.org/x/crypto/curve25519/internal/field/sync.checkpoint
  vendor/golang.org/x/crypto/curve25519/internal/field/sync.sh
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/go115.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/not_go115.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/write.go
  vendor/modules.txt
Labels: api/microsoft-graph, bug, feature/groups

#455 Bump Hamilton to v0.16.0
  go.mod
  go.sum
  vendor/github.com/manicminer/hamilton/msgraph/app_role_assignments.go
  vendor/github.com/manicminer/hamilton/msgraph/applications.go
  vendor/github.com/manicminer/hamilton/msgraph/client.go
  vendor/github.com/manicminer/hamilton/msgraph/conditionalaccesspolicy.go
  vendor/github.com/manicminer/hamilton/msgraph/directory_role_templates.go
  vendor/github.com/manicminer/hamilton/msgraph/directory_roles.go
  vendor/github.com/manicminer/hamilton/msgraph/domains.go
  vendor/github.com/manicminer/hamilton/msgraph/groups.go
  vendor/github.com/manicminer/hamilton/msgraph/identity_providers.go
  vendor/github.com/manicminer/hamilton/msgraph/namedlocations.go
  vendor/github.com/manicminer/hamilton/msgraph/serviceprincipals.go
  vendor/github.com/manicminer/hamilton/msgraph/users.go
  vendor/github.com/manicminer/hamilton/odata/odata.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.s
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/curve25519_amd64.go
  vendor/golang.org/x/crypto/curve25519/curve25519_amd64.s
  vendor/golang.org/x/crypto/curve25519/curve25519_generic.go
  vendor/golang.org/x/crypto/curve25519/curve25519_noasm.go
  vendor/golang.org/x/crypto/curve25519/internal/field/README
  vendor/golang.org/x/crypto/curve25519/internal/field/fe.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.s
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64_noasm.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64.s
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_arm64_noasm.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_generic.go
  vendor/golang.org/x/crypto/curve25519/internal/field/sync.checkpoint
  vendor/golang.org/x/crypto/curve25519/internal/field/sync.sh
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/go115.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/not_go115.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/write.go
  vendor/modules.txt
Labels: dependencies

#457 Improve docs around scope IDs for applications
  docs/resources/application.md
  examples/application/locals.tf
  examples/application/main.tf
  examples/create-for-rbac/main.tf
Labels: documentation

#465 Deprecation notices for application_oauth2_permission{,_scope} and azuread_application_app_role resources
  docs/guides/microsoft-graph.md
  internal/services/applications/application_app_role_resource.go
  internal/services/applications/application_oauth2_permission_resource.go
  internal/services/applications/application_oauth2_permission_scope_resource.go
Labels: feature/application
