Repository hashicorp/terraform-provider-azuread, pull requests merged in 2022-08, with the labels that each got.

#844 Fix for Issue #843 - end_date_relative for application_password
  internal/helpers/credentials.go
Labels: enhancement, size/M, feature/service-principal, feature/application

#870 Add warning that OIDC auth only works in GitHub Actions
  docs/guides/service_principal_oidc.md
Labels: size/XS, documentation, authentication

#873 Update to Go 1.19
  .github/workflows/depscheck.yml
  .github/workflows/docs-lint.yml
  .github/workflows/golint.yml
  .github/workflows/teamcity-test.yml
  .github/workflows/tflint.yml
  .github/workflows/thirty-two-bit.yml
  .github/workflows/unit-test.yml
  .go-version
  GNUmakefile
  go.mod
  go.sum
Labels: size/L, dependencies

#858 Docs: azuread_group.dynamic_membership.rule is required, not optional
  docs/resources/group.md
Labels: size/XS, feature/groups

#864 Add Support for optional additional property
  internal/services/applications/schema.go
Labels: enhancement, size/XS, feature/application

#874 Support for generic OIDC providers
  docs/guides/service_principal_oidc.md
  docs/index.md
  go.mod
  go.sum
  internal/provider/provider.go
  internal/provider/provider_test.go
  vendor/github.com/manicminer/hamilton/auth/auth.go
  vendor/github.com/manicminer/hamilton/auth/config.go
  vendor/github.com/manicminer/hamilton/msgraph/models.go
  vendor/github.com/manicminer/hamilton/msgraph/synchronization.go
  vendor/github.com/manicminer/hamilton/odata/types.go
  vendor/modules.txt
Labels: enhancement, documentation, size/XL, dependencies, authentication

#876 Bugfix: incorrect OIDC method selection
  .github/workflows/acctest-oidc.yaml
  go.mod
  go.sum
  vendor/github.com/manicminer/hamilton/auth/auth.go
  vendor/modules.txt
Labels: bug, size/S, dependencies, tests
