Repository hashicorp/terraform-provider-azuread, pull requests merged in 2022-04, with the labels that each got.

#766 Add Resources for Claims Mapping Policy Management
  .teamcity/components/project.kt
  docs/resources/claims_mapping_policy.md
  docs/resources/service_principal_claims_mapping_policy_assignment.md
  internal/clients/client.go
  internal/provider/services.go
  internal/services/policies/claims_mapping_policy_resource.go
  internal/services/policies/claims_mapping_policy_resource_test.go
  internal/services/policies/client/client.go
  internal/services/policies/registration.go
  internal/services/serviceprincipals/client/client.go
  internal/services/serviceprincipals/parse/claims_mapping_policy_assignment.go
  internal/services/serviceprincipals/registration.go
  internal/services/serviceprincipals/service_principal_claims_mapping_policy_assignment_resource.go
  internal/services/serviceprincipals/service_principal_claims_mapping_policy_assignment_resource_test.go
Labels: new-resource, size/XL

#767 Migrate to GitHub Actions based releases
  .github/workflows/release.yml
  .goreleaser.yml
  .tfproto5
  scripts/changelog-links.sh
  scripts/release.sh
  terraform-registry-manifest.json
Labels: size/L, tooling

#769 Update claims_mapping_policy.md
  docs/resources/claims_mapping_policy.md
Labels: size/XS, documentation, feature/policies

#772 Remove extraneous whitespace, doc not parsing correctly
  docs/resources/service_principal_claims_mapping_policy_assignment.md
Labels: size/XS, feature/policies

#770 Improve release script
  scripts/release.sh
Labels: size/M, tooling

#786 Update Hamilton to v0.46.0
  go.mod
  go.sum
  vendor/github.com/manicminer/hamilton/environments/published.go
  vendor/github.com/manicminer/hamilton/msgraph/valuetypes.go
  vendor/modules.txt
Labels: size/XS, dependencies

#781 Bugfix: raise error when multiple results are found for `azuread_service_principal` data source
  internal/services/serviceprincipals/service_principal_data_source.go
  internal/services/serviceprincipals/service_principal_data_source_test.go
Labels: bug, size/S, feature/service-principal

#783 `data.azuread_groups` - support the `ignore_missing` property
  docs/data-sources/groups.md
  docs/data-sources/users.md
  internal/helpers/consistency.go
  internal/services/groups/group_resource.go
  internal/services/groups/group_resource_test.go
  internal/services/groups/groups_data_source.go
  internal/services/groups/groups_data_source_test.go
Labels: enhancement, size/L, feature/groups, api-bug
