Repository hashicorp/terraform-provider-azuread, pull requests merged in 2022-06, with the labels that each got.

#795 Updated Conditional Access Policy documentation
  docs/resources/conditional_access_policy.md
Labels: size/XS, documentation, feature/conditional-access

#816 Bugfix: nil check the result of WaitForUpdateWithTimeout
  internal/helpers/consistency.go
Labels: bug, size/XS, crash, feature/groups

#815 azuread_user: user_principal_name should not be ForceNew
  internal/services/users/user_resource.go
  internal/services/users/user_resource_test.go
Labels: enhancement, size/XS, feature/users

#805 Support for OIDC Authentication
  docs/guides/azure_cli.md
  docs/guides/managed_service_identity.md
  docs/guides/service_principal_client_certificate.md
  docs/guides/service_principal_client_secret.md
  docs/guides/service_principal_oidc.md
  docs/index.md
  internal/provider/provider.go
  internal/provider/provider_test.go
Labels: enhancement, size/L, authentication

#817 Docs: Policy.Read.All role is required for azuread_claims_mapping_policy
  docs/resources/claims_mapping_policy.md
Labels: size/XS, feature/policies

#819 Bugfix: set the tenant ID correctly when not specified by provider block
  internal/clients/builder.go
Labels: bug, size/XS, authentication

#822 Bugfix: set correct values for IDTokenRequestURL and IDTokenRequestToken
  internal/provider/provider.go
Labels: size/XS

#826 New resource: `azuread_directory_role_assignment`
  docs/resources/directory_role_assignment.md
  docs/resources/directory_role_member.md
  internal/services/directoryroles/client/client.go
  internal/services/directoryroles/directory_role_assignment_resource.go
  internal/services/directoryroles/directory_role_assignment_resource_test.go
  internal/services/directoryroles/directory_role_member_resource.go
  internal/services/directoryroles/registration.go
Labels: new-resource, size/XL, feature/directory-roles
