Repository hashicorp/terraform-provider-azuread, pull requests merged in 2023-06, with the labels that each got.

#1123 provider: ensuring the provider version is appended to the release user agent
  .goreleaser.yml
Labels: size/XS, provider

#1129 User Resource - Country Code Examples unified.
  docs/resources/user.md
Labels: size/XS

#1130 tooling: updating the TeamCity configuration
  .github/workflows/teamcity-test.yaml
  .teamcity/components/build_azure.kt
  .teamcity/components/build_components.kt
  .teamcity/components/build_config_pull_request.kt
  .teamcity/components/build_config_service.kt
  .teamcity/components/project.kt
  .teamcity/components/vcs_root.kt
  .teamcity/pom.xml
  .teamcity/settings.kts
Labels: size/S, tooling
