Repository hashicorp/terraform-provider-azuread, pull requests merged in 2023-05, with the labels that each got.

#1096 Tooling: pin all GitHub workflows
  .github/workflows/acctest-oidc.yaml
  .github/workflows/depscheck.yaml
  .github/workflows/docs-lint.yaml
  .github/workflows/golint.yaml
  .github/workflows/issue-comment-created.yaml
  .github/workflows/issue-opened.yaml
  .github/workflows/link-milestone.yaml
  .github/workflows/lock.yaml
  .github/workflows/milestone-closed.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release.yaml
  .github/workflows/teamcity-test.yaml
  .github/workflows/tflint.yaml
  .github/workflows/thirty-two-bit.yaml
  .github/workflows/unit-test.yaml
  .github/workflows/validate-examples.yaml
Labels: size/M, tooling

#1098 Fix typo on debugging docs
  docs/index.md
Labels: size/XS, documentation

#1111 Bump all GitHub Actions and pin; avoid deprecated Node 12
  .github/workflows/acctest-oidc.yaml
  .github/workflows/depscheck.yaml
  .github/workflows/docs-lint.yaml
  .github/workflows/golint.yaml
  .github/workflows/link-milestone.yaml
  .github/workflows/teamcity-test.yaml
  .github/workflows/tflint.yaml
  .github/workflows/thirty-two-bit.yaml
  .github/workflows/unit-test.yaml
  .github/workflows/validate-examples.yaml
Labels: size/XS, tooling
