Repository hashicorp/terraform-provider-azuread, pull requests merged in 2024-10, with the labels that each got.

#1518 `azuread_group` - Fix crash and memory leak
  internal/services/groups/group_resource.go
  internal/services/groups/group_resource_test.go
Labels: size/XS, feature/groups

#1529 Removing references to "hashitown" domain
  docs/resources/application_identifier_uri.md
  docs/resources/application_owner.md
  docs/resources/application_redirect_uris.md
  docs/resources/application_registration.md
  internal/services/applications/application_data_source_test.go
  internal/services/applications/application_federated_identity_credential_resource_test.go
  internal/services/applications/application_redirect_uris_resource_test.go
  internal/services/applications/application_registration_resource_test.go
  internal/services/applications/application_resource_test.go
  internal/services/serviceprincipals/service_principal_resource_test.go
Labels: size/M, documentation, feature/service-principals, feature/applications

#1519 Update import documentation for user and group
  docs/resources/group.md
  docs/resources/user.md
Labels: size/XS, documentation

#1524 Add /servicePrincipals/ prefix to import in docs
  docs/resources/service_principal.md
Labels: size/XS, documentation

#1512 Fix error message typo
  internal/services/applications/application_registration_resource.go
Labels: size/XS, feature/applications

#1516 docs: Fix formatting of directory_object
  docs/data-sources/directory_object.md
Labels: size/XS, documentation

#1533 Add CODEOWNERS & META.d
  CODEOWNERS
  META.d/_summary.yaml
Labels: size/XS

#1430 bugfix: azuread_application - delete password block
  internal/services/applications/application_password_resource_test.go
  internal/services/applications/application_resource.go
  internal/services/applications/application_resource_test.go
Labels: size/M, feature/applications

#1397 docs: correct `identity` snippet in doc
  docs/guides/managed_service_identity.md
Labels: size/XS, documentation
