Repository hashicorp/terraform-provider-azuread, pull requests merged in 2025-05, with the labels that each got.

#1663 Update redirect URI validation to support `brk-multihub://` as a valid redirect URI scheme
  internal/helpers/tf/validation/uri.go
Labels: size/XS

#1697 update golint action to v1.64.8
  .github/workflows/golint.yaml
Labels: size/XS, tooling

#1693 fix typo in example usage of azuread_administrative_unit_role_member resource
  docs/resources/administrative_unit_role_member.md
Labels: size/XS, documentation

#1689 tooling: Onboard to CRT
  .github/workflows/build.yml
  .release/ci.hcl
  .release/release-metadata.hcl
  .release/security-scan.hcl
  .release/terraform-provider-azuread-artifacts.hcl
  version/VERSION
Labels: size/XL, tooling

#1601 azuread_conditional_access_policy: Fix `external_tenants` with `enumerated` members
  internal/services/conditionalaccess/conditional_access_policy_resource_test.go
  internal/services/conditionalaccess/conditionalaccess.go
Labels: size/M, feature/conditional-access

#1698 changelog for v3.4.0
  CHANGELOG.md
  version/VERSION
Labels: size/XS
